import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from 'antd';
import { DatePicker, Space } from 'antd';
import moment from 'moment';
import { Row, Col } from 'antd';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.wrapper__collection__section}>
        <Row justify="space-around">
          <Col xs={{ span: 24 }} md={{ span: 7 }}>
            <div className={styles.card__collection}>
              <div className={styles.content}>
                <h2 className={styles.title}>TitleTitleTitle</h2>
                <p className={styles.description}>TitleTitleTitle</p>
                <button className={styles.btn__buy}>Xem ngay</button>
              </div>
            </div>
          </Col>
          <Col xs={{ span: 24 }} md={{ span: 7 }}>
            <div className={styles.card__collection}>
              <div className={styles.content}>
                <h2 className={styles.title}>TitleTitleTitle</h2>
                <p className={styles.description}>TitleTitleTitle</p>
                <button className={styles.btn__buy}>Xem ngay</button>
              </div>
            </div>
          </Col>
          <Col xs={{ span: 24 }} md={{ span: 7 }}>
            <div className={styles.card__collection}>
              <div className={styles.content}>
                <h2 className={styles.title}>TitleTitleTitle</h2>
                <p className={styles.description}>TitleTitleTitle</p>
                <button className={styles.btn__buy}>Xem ngay</button>
              </div>
            </div>
          </Col>
        </Row>
      </section>

      <section className={styles.latest__product}>
        <h3 className={styles.title}>latest product</h3>

        <Row justify="space-around">
          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>

          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>

          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>

          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>
        </Row>
        <br />
        <Row justify="space-around">
          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>

          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>

          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>

          <Col xs={{ span: 24 }} md={{ span: 5 }}>
            <div className={styles.card}>
              <div className={styles.imgBx}>
                <img src="/images/product_2.png" />
              </div>
              <div className={styles.contentBx}>
                <h3>ROBOT ASFSAFAE</h3>
                <h2 className={styles.price}>
                  $245
                  <small>.99</small>
                </h2>
                <a href="#" className={styles.buy}>Mua ngay</a>
              </div>
            </div>
          </Col>
        </Row>
      </section>

      <section className={styles.newest__product}>
        <div className={styles.content}>
          <div className={styles.imageBox}>
            <img src="/images/product.png" alt="" />
          </div>
          <div className={styles.contentBox}>
              <h2 className={styles.title}>robot 123dfdsgsdgasd</h2>
              <p className={styles.description}>
                robot 123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd
                123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd123dfdsgsdgasd
              </p>
              <button className={styles.button__detail}>Xem Chi Tiết</button>
          </div>
        </div>
      </section>
    </div>
  )
}
